name: Deploy

on:
  push:
    branches: [ staging ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Run Babel
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: apex/actions/up@v0.5.1
        env:
          # This will be your prod acct keys
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          stage: production